language: node_js

# build matrix for testing tasks

sudo: required

os:
  - linux
  - osx

node_js:
  - "node" # latest stable Node.js release
  - "7"
  - "6"

env:
  - BUILD_ENV=production
  - BUILD_ENV=development

cache:
  directories:
    - node_modules

install:
  - npm install && sudo apt-get install tree

script:
  - ./node_modules/.bin/gulp ci:test

# build on specific versions intended for deployment

matrix:
  include:
    - os: linux
      env:
        - BUILD_ENV=production
      node_js: "7.3.0"
      script: ./node_modules/.bin/gulp ci:deploy && tree dist
