language: node_js

os:
  - linux
  - osx

node_js:
  - "7"
  - "6"

install:
  - npm install

script:
  - ./node_modules/.bin/gulp test:with-coverage

after_success:
  - ./node_modules/.bin/gulp test:coveralls
