language: node_js

os:
  - linux
  - osx

node_js:
  - "7"
  - "6"

install:
  - npm install

script:
  - ./node_modules/.bin/gulp test:coverage

after_success:
  - ./node_modules/.bin/gulp test:coveralls

before-deploy:
  - ./node_modules/.bin/gulp prepare-dirs
  - ./node_modules/.bin/gulp compile

deploy:
  - ./node_modules/.bin/gulp deploy
