language: node_js

os:
  - linux
  - osx

node_js:
  - "7"
  - "6"

env:
  global:
    - CI_BUILD=1

matrix:
  include:
  - node_js: "7.2.0"
    script: ./node_modules/.bin/gulp ci:deploy

install:
  - npm install

script:
  - ./node_modules/.bin/gulp ci:test
