language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "6"
  - "6.3"
  - "6.2"
  - "6.1"
  - "6.0"

before_install:
  - cd app

install:
  - npm install

script:
  - npm run lint
  - npm run test

after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
