language: node_js

# Build matrix

os:
  - linux
  - osx

node_js:
  - "node" # latest node
  - "6" # latest 6.x.x node

# Build lifecycle

before_install:
  - cd app
  - chmod +x scripts/install.sh

install:
  - ./scripts/install.sh

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coveralls
