language: node_js

# build matrix for testing tasks

os:
  - linux
  - osx

node_js:
  - "node" # latest stable Node.js release
  - "7"
  - "6"

env:
  - NODE_ENV=production
  - NODE_ENV=development
  - BUILD_ENV=production
  - BUILD_ENV=development

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - ./node_modules/.bin/gulp ci:test

# build on specific versions intended for deployment

matrix:
  include:
    - os: linux
      env:
        - NODE_ENV=production
        - BUILD_ENV=production
      node_js: "7.3.0"
      script: ./node_modules/.bin/gulp ci:deploy
