language: node_js

# build matrix for testing tasks

os:
  - linux
  - osx

node_js:
  - "node" # latest stable Node.js release
  - "8"
  - "7"

script:
  - ./node_modules/.bin/gulp ci:test

# build on specific version for deployment task

matrix:
  include:
    - os: linux
      node_js: "8.2.1"
      script: ./node_modules/.bin/gulp ci:deploy
