language: node_js

os:
  - linux
  - osx

node_js:
  - "7"
  - "6"

env:
  global:
    - CI_BUILD=1
    - TEST_SUITE=test

matrix:
  include:
  - node_js: "7.2.0"
    env: TEST_SUITE=deploy
    script: ./node_modules/.bin/gulp ci:deploy

install:
  - npm install

script:
  - ./node_modules/.bin/gulp ci:test
