language: node_js

# build matrix for testing tasks

os:
  - linux
  - osx

node_js:
  - "node" # latest stable Node.js release
  - "7"
  - "6"

install:
  - npm install

script:
  - ./node_modules/.bin/gulp ci:test

# build on specific versions intended for deployment

matrix:
  include:
  - os: linux
    node_js: "7.2.0"
    env: NODE_ENV=production
    script: ./node_modules/.bin/gulp ci:deploy
