language: node_js

# Build matrix for testing tasks

os:
  - linux
  - osx

node_js:
  - "node" # latest stable Node.js release
  - "8"

script:
  - ./node_modules/.bin/gulp ci:test

# Build on specific version for deployment task

matrix:
  include:
    - os: linux
      node_js: "8.9.3"
      script: ./node_modules/.bin/gulp ci:deploy
