language: node_js

# Build matrix

os:
  - linux
  - osx

node_js:
  - "node"
  - "6"
  - "6.3"
  - "6.2"
  - "6.1"
  - "6.0"

# Build lifecycle

before_install:
  - cd app
  - chmod +x scripts/install.sh

install:
  - ./scripts/install.sh

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coveralls
