language: node_js

# Build matrix

os:
  - linux
  - osx

node_js:
  - "node" # latest node
  - "7" # latest 7.x.x node
  - "6"

# Build lifecycle

before_install:
  - cd app
  - chmod +x scripts/prepare-dirs.sh

install:
  - ./scripts/prepare-dirs.sh
  - npm install

script:
  - npm run lint
  - npm run test+coverage

after_success:
  - npm run coveralls
