version: '2.1'

services:
  blog-app:
    # container_name: xxx
    build: .
    ports:
      - "8000:8000"
    restart: always
    # volumes:
    #   - ./src:/usr/src/blog/app/src
    environment:
      NODE_ENV: development

  blog-db:
    image: mysql:5.7.16
    # volumes:
    #   - "./.data/db:/var/lib/mysql"
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hurtak_blog
