version: '2'
services:
    blog:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
        redis:
        image: redis
